// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlcgen

import (
	"context"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_id, actor_role, action, resource_type, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
`

type InsertAuditEventParams struct {
	ActorID      *string `json:"actor_id"`
	ActorRole    *string `json:"actor_role"`
	Action       string  `json:"action"`
	ResourceType *string `json:"resource_type"`
	ResourceID   *string `json:"resource_id"`
	Metadata     []byte  `json:"metadata"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many

SELECT id, actor_id, actor_role, action, resource_type, resource_id, metadata, created_at
FROM audit_events
ORDER BY created_at DESC
LIMIT $1
`

// 审计查询（复刻 Java AuditController / AuditService）。
func (q *Queries) ListAuditEvents(ctx context.Context, lim int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByResourceType = `-- name: ListAuditEventsByResourceType :many
SELECT id, actor_id, actor_role, action, resource_type, resource_id, metadata, created_at
FROM audit_events
WHERE resource_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditEventsByResourceTypeParams struct {
	ResourceType *string `json:"resource_type"`
	Lim          int32   `json:"lim"`
}

func (q *Queries) ListAuditEventsByResourceType(ctx context.Context, arg ListAuditEventsByResourceTypeParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByResourceType, arg.ResourceType, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceInstanceChecked = `-- name: UpdateServiceInstanceChecked :execrows
UPDATE service_instances SET last_checked_at = now() WHERE name = $1
`

func (q *Queries) UpdateServiceInstanceChecked(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceInstanceChecked, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
