// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: config.sql

package sqlcgen

import (
	"context"
	"time"
)

const activateConfigVersion = `-- name: ActivateConfigVersion :exec
UPDATE config_versions SET status = 'active' WHERE config_item_id = $1::uuid AND version = $2
`

type ActivateConfigVersionParams struct {
	ConfigItemID string `json:"config_item_id"`
	Version      int32  `json:"version"`
}

func (q *Queries) ActivateConfigVersion(ctx context.Context, arg ActivateConfigVersionParams) error {
	_, err := q.db.Exec(ctx, activateConfigVersion, arg.ConfigItemID, arg.Version)
	return err
}

const archiveConfigVersions = `-- name: ArchiveConfigVersions :exec
UPDATE config_versions SET status = 'archived' WHERE config_item_id = $1::uuid
`

func (q *Queries) ArchiveConfigVersions(ctx context.Context, configItemID string) error {
	_, err := q.db.Exec(ctx, archiveConfigVersions, configItemID)
	return err
}

const countConfigVersion = `-- name: CountConfigVersion :one
SELECT COUNT(*)::int AS n
FROM config_versions WHERE config_item_id = $1::uuid AND version = $2
`

type CountConfigVersionParams struct {
	ConfigItemID string `json:"config_item_id"`
	Version      int32  `json:"version"`
}

func (q *Queries) CountConfigVersion(ctx context.Context, arg CountConfigVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, countConfigVersion, arg.ConfigItemID, arg.Version)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createConfigItem = `-- name: CreateConfigItem :one
INSERT INTO config_items (env, namespace, config_key, config_type, active_version, status, created_by)
VALUES ($1, $2, $3, $4, 1, 'active', $5)
RETURNING id
`

type CreateConfigItemParams struct {
	Env        string  `json:"env"`
	Namespace  *string `json:"namespace"`
	ConfigKey  string  `json:"config_key"`
	ConfigType string  `json:"config_type"`
	CreatedBy  *string `json:"created_by"`
}

func (q *Queries) CreateConfigItem(ctx context.Context, arg CreateConfigItemParams) (string, error) {
	row := q.db.QueryRow(ctx, createConfigItem,
		arg.Env,
		arg.Namespace,
		arg.ConfigKey,
		arg.ConfigType,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getConfigActiveVersion = `-- name: GetConfigActiveVersion :one
SELECT active_version FROM config_items WHERE id = $1::uuid
`

func (q *Queries) GetConfigActiveVersion(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, getConfigActiveVersion, id)
	var active_version int32
	err := row.Scan(&active_version)
	return active_version, err
}

const getConfigKey = `-- name: GetConfigKey :one
SELECT config_key FROM config_items WHERE id = $1::uuid
`

func (q *Queries) GetConfigKey(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getConfigKey, id)
	var config_key string
	err := row.Scan(&config_key)
	return config_key, err
}

const insertConfigVersion = `-- name: InsertConfigVersion :exec
INSERT INTO config_versions (config_item_id, version, content, change_reason, operator, status)
VALUES ($1::uuid, $2, $3, $4, $5, $6)
`

type InsertConfigVersionParams struct {
	ConfigItemID string  `json:"config_item_id"`
	Version      int32   `json:"version"`
	Content      *string `json:"content"`
	ChangeReason *string `json:"change_reason"`
	Operator     *string `json:"operator"`
	Status       string  `json:"status"`
}

func (q *Queries) InsertConfigVersion(ctx context.Context, arg InsertConfigVersionParams) error {
	_, err := q.db.Exec(ctx, insertConfigVersion,
		arg.ConfigItemID,
		arg.Version,
		arg.Content,
		arg.ChangeReason,
		arg.Operator,
		arg.Status,
	)
	return err
}

const listConfigItems = `-- name: ListConfigItems :many

SELECT c.id, c.env, c.namespace, c.config_key, c.config_type,
       c.active_version, c.status, c.created_by, c.updated_at,
       COUNT(v.id)::int AS version_count
FROM config_items c
LEFT JOIN config_versions v ON v.config_item_id = c.id
GROUP BY c.id
ORDER BY c.updated_at DESC
`

type ListConfigItemsRow struct {
	ID            string    `json:"id"`
	Env           string    `json:"env"`
	Namespace     *string   `json:"namespace"`
	ConfigKey     string    `json:"config_key"`
	ConfigType    string    `json:"config_type"`
	ActiveVersion int32     `json:"active_version"`
	Status        string    `json:"status"`
	CreatedBy     *string   `json:"created_by"`
	UpdatedAt     time.Time `json:"updated_at"`
	VersionCount  int32     `json:"version_count"`
}

// 配置中心查询（复刻 Java ConfigController）。
// uuid 参数用 sqlc.arg(name)::uuid：既显式转换、又让 sqlc 生成具名字段（非 Column1）。
func (q *Queries) ListConfigItems(ctx context.Context) ([]ListConfigItemsRow, error) {
	rows, err := q.db.Query(ctx, listConfigItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigItemsRow{}
	for rows.Next() {
		var i ListConfigItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Env,
			&i.Namespace,
			&i.ConfigKey,
			&i.ConfigType,
			&i.ActiveVersion,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.VersionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigVersions = `-- name: ListConfigVersions :many
SELECT version, content, change_reason, operator, status, created_at
FROM config_versions
WHERE config_item_id = $1::uuid
ORDER BY version DESC
`

type ListConfigVersionsRow struct {
	Version      int32     `json:"version"`
	Content      *string   `json:"content"`
	ChangeReason *string   `json:"change_reason"`
	Operator     *string   `json:"operator"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListConfigVersions(ctx context.Context, configItemID string) ([]ListConfigVersionsRow, error) {
	rows, err := q.db.Query(ctx, listConfigVersions, configItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigVersionsRow{}
	for rows.Next() {
		var i ListConfigVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Content,
			&i.ChangeReason,
			&i.Operator,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxConfigVersion = `-- name: MaxConfigVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM config_versions WHERE config_item_id = $1::uuid
`

func (q *Queries) MaxConfigVersion(ctx context.Context, configItemID string) (int32, error) {
	row := q.db.QueryRow(ctx, maxConfigVersion, configItemID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const setConfigItemActiveVersion = `-- name: SetConfigItemActiveVersion :exec
UPDATE config_items SET active_version = $1, updated_at = now() WHERE id = $2::uuid
`

type SetConfigItemActiveVersionParams struct {
	ActiveVersion int32  `json:"active_version"`
	ID            string `json:"id"`
}

func (q *Queries) SetConfigItemActiveVersion(ctx context.Context, arg SetConfigItemActiveVersionParams) error {
	_, err := q.db.Exec(ctx, setConfigItemActiveVersion, arg.ActiveVersion, arg.ID)
	return err
}
