// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deployment.sql

package sqlcgen

import (
	"context"
	"time"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (deployment_key, version, env, status, started_at, metadata)
VALUES ($1, $2, $3, 'running', now(), $4::jsonb)
RETURNING id
`

type CreateDeploymentParams struct {
	DeploymentKey *string `json:"deployment_key"`
	Version       *string `json:"version"`
	Env           *string `json:"env"`
	Metadata      []byte  `json:"metadata"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (string, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.DeploymentKey,
		arg.Version,
		arg.Env,
		arg.Metadata,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployments SET status = $1, finished_at = now() WHERE id = $2::uuid
`

type FinishDeploymentParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.Exec(ctx, finishDeployment, arg.Status, arg.ID)
	return err
}

const getDeploymentForRollback = `-- name: GetDeploymentForRollback :one
SELECT deployment_key, version, env, metadata FROM deployments WHERE id = $1::uuid
`

type GetDeploymentForRollbackRow struct {
	DeploymentKey *string `json:"deployment_key"`
	Version       *string `json:"version"`
	Env           *string `json:"env"`
	Metadata      []byte  `json:"metadata"`
}

func (q *Queries) GetDeploymentForRollback(ctx context.Context, id string) (GetDeploymentForRollbackRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentForRollback, id)
	var i GetDeploymentForRollbackRow
	err := row.Scan(
		&i.DeploymentKey,
		&i.Version,
		&i.Env,
		&i.Metadata,
	)
	return i, err
}

const getDeploymentKey = `-- name: GetDeploymentKey :one
SELECT deployment_key FROM deployments WHERE id = $1::uuid
`

func (q *Queries) GetDeploymentKey(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getDeploymentKey, id)
	var deployment_key *string
	err := row.Scan(&deployment_key)
	return deployment_key, err
}

const listDeployments = `-- name: ListDeployments :many

SELECT id, deployment_key, version, env, status, started_at, finished_at, metadata
FROM deployments
ORDER BY started_at DESC NULLS LAST, id DESC
LIMIT 100
`

type ListDeploymentsRow struct {
	ID            string     `json:"id"`
	DeploymentKey *string    `json:"deployment_key"`
	Version       *string    `json:"version"`
	Env           *string    `json:"env"`
	Status        string     `json:"status"`
	StartedAt     *time.Time `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	Metadata      []byte     `json:"metadata"`
}

// 发布流水线查询（复刻 Java DeploymentController）。
func (q *Queries) ListDeployments(ctx context.Context) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsRow{}
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentKey,
			&i.Version,
			&i.Env,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentRolledBack = `-- name: MarkDeploymentRolledBack :exec
UPDATE deployments SET status = 'rolled_back', finished_at = now() WHERE id = $1::uuid
`

func (q *Queries) MarkDeploymentRolledBack(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markDeploymentRolledBack, id)
	return err
}
