// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: diagnose.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiagnosis = `-- name: GetDiagnosis :one
SELECT id, question, status, root_cause, confidence, impact,
       evidence, recommended_actions, related_resources,
       model_id, endpoint_id, latency_ms, error, created_at
FROM diagnoses WHERE id = $1::uuid
`

func (q *Queries) GetDiagnosis(ctx context.Context, id string) (Diagnosis, error) {
	row := q.db.QueryRow(ctx, getDiagnosis, id)
	var i Diagnosis
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Status,
		&i.RootCause,
		&i.Confidence,
		&i.Impact,
		&i.Evidence,
		&i.RecommendedActions,
		&i.RelatedResources,
		&i.ModelID,
		&i.EndpointID,
		&i.LatencyMs,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const insertDiagnosis = `-- name: InsertDiagnosis :one

INSERT INTO diagnoses (
    question, status, root_cause, confidence, impact,
    evidence, recommended_actions, related_resources,
    model_id, endpoint_id, latency_ms, error
) VALUES (
    $1, $2, $3, $4, $5,
    $6::jsonb, $7::jsonb, $8::jsonb,
    $9, $10, $11, $12
)
RETURNING id
`

type InsertDiagnosisParams struct {
	Question           string         `json:"question"`
	Status             string         `json:"status"`
	RootCause          *string        `json:"root_cause"`
	Confidence         pgtype.Numeric `json:"confidence"`
	Impact             *string        `json:"impact"`
	Evidence           []byte         `json:"evidence"`
	RecommendedActions []byte         `json:"recommended_actions"`
	RelatedResources   []byte         `json:"related_resources"`
	ModelID            *string        `json:"model_id"`
	EndpointID         *string        `json:"endpoint_id"`
	LatencyMs          pgtype.Numeric `json:"latency_ms"`
	Error              *string        `json:"error"`
}

// AI 诊断查询（Phase 3）。
func (q *Queries) InsertDiagnosis(ctx context.Context, arg InsertDiagnosisParams) (string, error) {
	row := q.db.QueryRow(ctx, insertDiagnosis,
		arg.Question,
		arg.Status,
		arg.RootCause,
		arg.Confidence,
		arg.Impact,
		arg.Evidence,
		arg.RecommendedActions,
		arg.RelatedResources,
		arg.ModelID,
		arg.EndpointID,
		arg.LatencyMs,
		arg.Error,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listDiagnoses = `-- name: ListDiagnoses :many
SELECT id, question, status, root_cause, confidence, impact,
       model_id, endpoint_id, latency_ms, error, created_at
FROM diagnoses
ORDER BY created_at DESC
LIMIT $1
`

type ListDiagnosesRow struct {
	ID         string         `json:"id"`
	Question   string         `json:"question"`
	Status     string         `json:"status"`
	RootCause  *string        `json:"root_cause"`
	Confidence pgtype.Numeric `json:"confidence"`
	Impact     *string        `json:"impact"`
	ModelID    *string        `json:"model_id"`
	EndpointID *string        `json:"endpoint_id"`
	LatencyMs  pgtype.Numeric `json:"latency_ms"`
	Error      *string        `json:"error"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) ListDiagnoses(ctx context.Context, lim int32) ([]ListDiagnosesRow, error) {
	rows, err := q.db.Query(ctx, listDiagnoses, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiagnosesRow{}
	for rows.Next() {
		var i ListDiagnosesRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Status,
			&i.RootCause,
			&i.Confidence,
			&i.Impact,
			&i.ModelID,
			&i.EndpointID,
			&i.LatencyMs,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
