// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: incident.sql

package sqlcgen

import (
	"context"
	"time"
)

const ackIncident = `-- name: AckIncident :exec
UPDATE incidents SET status = 'acknowledged' WHERE id = $1::uuid
`

func (q *Queries) AckIncident(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, ackIncident, id)
	return err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (title, severity, status, summary)
VALUES ($1, $2, 'open', $3)
RETURNING id
`

type CreateIncidentParams struct {
	Title    string  `json:"title"`
	Severity string  `json:"severity"`
	Summary  *string `json:"summary"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (string, error) {
	row := q.db.QueryRow(ctx, createIncident, arg.Title, arg.Severity, arg.Summary)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, severity, status, summary, created_at, resolved_at
FROM incidents WHERE id = $1::uuid
`

type GetIncidentRow struct {
	ID         string     `json:"id"`
	Title      string     `json:"title"`
	Severity   string     `json:"severity"`
	Status     string     `json:"status"`
	Summary    *string    `json:"summary"`
	CreatedAt  time.Time  `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at"`
}

func (q *Queries) GetIncident(ctx context.Context, id string) (GetIncidentRow, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i GetIncidentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertIncidentEvent = `-- name: InsertIncidentEvent :exec
INSERT INTO incident_events (incident_id, event_type, payload)
VALUES ($1::uuid, $2, $3::jsonb)
`

type InsertIncidentEventParams struct {
	IncidentID string  `json:"incident_id"`
	EventType  *string `json:"event_type"`
	Payload    []byte  `json:"payload"`
}

func (q *Queries) InsertIncidentEvent(ctx context.Context, arg InsertIncidentEventParams) error {
	_, err := q.db.Exec(ctx, insertIncidentEvent, arg.IncidentID, arg.EventType, arg.Payload)
	return err
}

const listIncidentEvents = `-- name: ListIncidentEvents :many
SELECT event_type, payload, created_at
FROM incident_events
WHERE incident_id = $1::uuid
ORDER BY created_at ASC
`

type ListIncidentEventsRow struct {
	EventType *string   `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListIncidentEvents(ctx context.Context, incidentID string) ([]ListIncidentEventsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentEventsRow{}
	for rows.Next() {
		var i ListIncidentEventsRow
		if err := rows.Scan(&i.EventType, &i.Payload, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many

SELECT id, title, severity, status, summary, created_at, resolved_at
FROM incidents
ORDER BY created_at DESC
LIMIT 100
`

type ListIncidentsRow struct {
	ID         string     `json:"id"`
	Title      string     `json:"title"`
	Severity   string     `json:"severity"`
	Status     string     `json:"status"`
	Summary    *string    `json:"summary"`
	CreatedAt  time.Time  `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at"`
}

// 故障事件查询（复刻 Java IncidentController）。
func (q *Queries) ListIncidents(ctx context.Context) ([]ListIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentsRow{}
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.Summary,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByStatus = `-- name: ListIncidentsByStatus :many
SELECT id, title, severity, status, summary, created_at, resolved_at
FROM incidents
WHERE status = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListIncidentsByStatusRow struct {
	ID         string     `json:"id"`
	Title      string     `json:"title"`
	Severity   string     `json:"severity"`
	Status     string     `json:"status"`
	Summary    *string    `json:"summary"`
	CreatedAt  time.Time  `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at"`
}

func (q *Queries) ListIncidentsByStatus(ctx context.Context, status string) ([]ListIncidentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listIncidentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentsByStatusRow{}
	for rows.Next() {
		var i ListIncidentsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.Summary,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIncident = `-- name: ResolveIncident :exec
UPDATE incidents SET status = 'resolved', resolved_at = now() WHERE id = $1::uuid
`

func (q *Queries) ResolveIncident(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resolveIncident, id)
	return err
}
