// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID          string    `json:"id"`
	AppKey      string    `json:"app_key"`
	Name        string    `json:"name"`
	Owner       *string   `json:"owner"`
	Env         string    `json:"env"`
	Description *string   `json:"description"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AuditEvent struct {
	ID           string    `json:"id"`
	ActorID      *string   `json:"actor_id"`
	ActorRole    *string   `json:"actor_role"`
	Action       string    `json:"action"`
	ResourceType *string   `json:"resource_type"`
	ResourceID   *string   `json:"resource_id"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
}

type BenchmarkRun struct {
	ID              string    `json:"id"`
	RunID           string    `json:"run_id"`
	EndpointID      *string   `json:"endpoint_id"`
	Workload        *string   `json:"workload"`
	RoutingStrategy *string   `json:"routing_strategy"`
	Status          string    `json:"status"`
	Config          []byte    `json:"config"`
	Summary         []byte    `json:"summary"`
	ReportPath      *string   `json:"report_path"`
	Error           *string   `json:"error"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type BenchmarkSample struct {
	ID        int64     `json:"id"`
	RunID     string    `json:"run_id"`
	EventType *string   `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type Cluster struct {
	ID         string    `json:"id"`
	ClusterKey string    `json:"cluster_key"`
	Name       string    `json:"name"`
	Provider   *string   `json:"provider"`
	Region     *string   `json:"region"`
	Status     string    `json:"status"`
	Metadata   []byte    `json:"metadata"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ConfigItem struct {
	ID            string    `json:"id"`
	AppID         *string   `json:"app_id"`
	Env           string    `json:"env"`
	Namespace     *string   `json:"namespace"`
	ConfigKey     string    `json:"config_key"`
	ConfigType    string    `json:"config_type"`
	ActiveVersion int32     `json:"active_version"`
	Status        string    `json:"status"`
	CreatedBy     *string   `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ConfigVersion struct {
	ID           string    `json:"id"`
	ConfigItemID string    `json:"config_item_id"`
	Version      int32     `json:"version"`
	Content      *string   `json:"content"`
	ChangeReason *string   `json:"change_reason"`
	Operator     *string   `json:"operator"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type Deployment struct {
	ID            string     `json:"id"`
	ServiceID     *string    `json:"service_id"`
	DeploymentKey *string    `json:"deployment_key"`
	Version       *string    `json:"version"`
	Env           *string    `json:"env"`
	Status        string     `json:"status"`
	StartedAt     *time.Time `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	Metadata      []byte     `json:"metadata"`
}

type Diagnosis struct {
	ID                 string         `json:"id"`
	Question           string         `json:"question"`
	Status             string         `json:"status"`
	RootCause          *string        `json:"root_cause"`
	Confidence         pgtype.Numeric `json:"confidence"`
	Impact             *string        `json:"impact"`
	Evidence           []byte         `json:"evidence"`
	RecommendedActions []byte         `json:"recommended_actions"`
	RelatedResources   []byte         `json:"related_resources"`
	ModelID            *string        `json:"model_id"`
	EndpointID         *string        `json:"endpoint_id"`
	LatencyMs          pgtype.Numeric `json:"latency_ms"`
	Error              *string        `json:"error"`
	CreatedAt          time.Time      `json:"created_at"`
}

type EvalRun struct {
	ID        string    `json:"id"`
	RunID     string    `json:"run_id"`
	ModelID   *string   `json:"model_id"`
	Dataset   *string   `json:"dataset"`
	Status    string    `json:"status"`
	Metrics   []byte    `json:"metrics"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Incident struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Severity         string     `json:"severity"`
	Status           string     `json:"status"`
	RelatedServiceID *string    `json:"related_service_id"`
	Summary          *string    `json:"summary"`
	DiagnosisID      *string    `json:"diagnosis_id"`
	CreatedAt        time.Time  `json:"created_at"`
	ResolvedAt       *time.Time `json:"resolved_at"`
}

type IncidentEvent struct {
	ID         string    `json:"id"`
	IncidentID string    `json:"incident_id"`
	EventType  *string   `json:"event_type"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
}

type K8sEvent struct {
	ID           string    `json:"id"`
	ClusterID    *string   `json:"cluster_id"`
	Namespace    *string   `json:"namespace"`
	ResourceKind *string   `json:"resource_kind"`
	ResourceName *string   `json:"resource_name"`
	Reason       *string   `json:"reason"`
	Message      *string   `json:"message"`
	Type         *string   `json:"type"`
	EventTime    time.Time `json:"event_time"`
}

type K8sResource struct {
	ID         string      `json:"id"`
	ClusterID  *string     `json:"cluster_id"`
	Namespace  *string     `json:"namespace"`
	Kind       string      `json:"kind"`
	Name       string      `json:"name"`
	Status     *string     `json:"status"`
	Ready      *string     `json:"ready"`
	Restarts   int32       `json:"restarts"`
	NodeName   *string     `json:"node_name"`
	PodIp      *netip.Addr `json:"pod_ip"`
	Labels     []byte      `json:"labels"`
	Raw        []byte      `json:"raw"`
	ObservedAt time.Time   `json:"observed_at"`
}

type KnowledgeChunk struct {
	ID           string    `json:"id"`
	DocumentID   string    `json:"document_id"`
	ChunkIndex   int32     `json:"chunk_index"`
	Content      *string   `json:"content"`
	EmbeddingRef *string   `json:"embedding_ref"`
	TokenCount   *int32    `json:"token_count"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
}

type KnowledgeDocument struct {
	ID        string    `json:"id"`
	DocID     string    `json:"doc_id"`
	Title     *string   `json:"title"`
	Content   *string   `json:"content"`
	Category  *string   `json:"category"`
	Version   *string   `json:"version"`
	SourceUri *string   `json:"source_uri"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type KnowledgeVersion struct {
	Version     string    `json:"version"`
	Description *string   `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type MetricsSample struct {
	ID        int64     `json:"id"`
	Source    *string   `json:"source"`
	Metrics   []byte    `json:"metrics"`
	CreatedAt time.Time `json:"created_at"`
}

type Model struct {
	ID            string    `json:"id"`
	ModelID       string    `json:"model_id"`
	DisplayName   *string   `json:"display_name"`
	BaseModel     *string   `json:"base_model"`
	ArtifactUri   *string   `json:"artifact_uri"`
	TokenizerUri  *string   `json:"tokenizer_uri"`
	Status        string    `json:"status"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Version       string    `json:"version"`
	LoraAdapter   *string   `json:"lora_adapter"`
	ParentVersion *string   `json:"parent_version"`
	Tags          []byte    `json:"tags"`
	CreatedBy     *string   `json:"created_by"`
}

type ModelAdapter struct {
	ID          string    `json:"id"`
	ModelID     *string   `json:"model_id"`
	AdapterID   string    `json:"adapter_id"`
	AdapterType *string   `json:"adapter_type"`
	ArtifactUri *string   `json:"artifact_uri"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

type Namespace struct {
	ID        string    `json:"id"`
	ClusterID *string   `json:"cluster_id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	Labels    []byte    `json:"labels"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PlatformService struct {
	ID          string    `json:"id"`
	AppID       *string   `json:"app_id"`
	ServiceKey  string    `json:"service_key"`
	Name        string    `json:"name"`
	Namespace   *string   `json:"namespace"`
	ServiceType *string   `json:"service_type"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RequestTrace struct {
	ID               string         `json:"id"`
	RequestID        string         `json:"request_id"`
	SessionID        *string        `json:"session_id"`
	EndpointID       *string        `json:"endpoint_id"`
	TargetPod        *string        `json:"target_pod"`
	ModelID          *string        `json:"model_id"`
	RetrievalMs      pgtype.Numeric `json:"retrieval_ms"`
	QueueOrGatewayMs pgtype.Numeric `json:"queue_or_gateway_ms"`
	TtftMs           pgtype.Numeric `json:"ttft_ms"`
	GenerationMs     pgtype.Numeric `json:"generation_ms"`
	TotalMs          pgtype.Numeric `json:"total_ms"`
	InputTokens      *int32         `json:"input_tokens"`
	OutputTokens     *int32         `json:"output_tokens"`
	Status           string         `json:"status"`
	Error            *string        `json:"error"`
	Metadata         []byte         `json:"metadata"`
	CreatedAt        time.Time      `json:"created_at"`
}

type RoutingPolicy struct {
	ID                string    `json:"id"`
	PolicyKey         string    `json:"policy_key"`
	ServiceInstanceID *string   `json:"service_instance_id"`
	Strategy          *string   `json:"strategy"`
	Weight            int32     `json:"weight"`
	Conditions        []byte    `json:"conditions"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ServiceDependency struct {
	ID              string    `json:"id"`
	SourceServiceID string    `json:"source_service_id"`
	TargetServiceID string    `json:"target_service_id"`
	DependencyType  *string   `json:"dependency_type"`
	Metadata        []byte    `json:"metadata"`
	CreatedAt       time.Time `json:"created_at"`
}

type ServiceInstance struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	BaseUrl         string     `json:"base_url"`
	ModelID         *string    `json:"model_id"`
	Kind            string     `json:"kind"`
	GpuID           *string    `json:"gpu_id"`
	RoutingRole     *string    `json:"routing_role"`
	ApiKey          *string    `json:"api_key"`
	Status          string     `json:"status"`
	LastCheckedAt   *time.Time `json:"last_checked_at"`
	Metadata        []byte     `json:"metadata"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	DisplayName *string   `json:"display_name"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
