// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: models.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteModelVersion = `-- name: DeleteModelVersion :one
DELETE FROM models WHERE id = $1::uuid
RETURNING model_id, version
`

type DeleteModelVersionRow struct {
	ModelID string `json:"model_id"`
	Version string `json:"version"`
}

func (q *Queries) DeleteModelVersion(ctx context.Context, id string) (DeleteModelVersionRow, error) {
	row := q.db.QueryRow(ctx, deleteModelVersion, id)
	var i DeleteModelVersionRow
	err := row.Scan(&i.ModelID, &i.Version)
	return i, err
}

const getModelVersion = `-- name: GetModelVersion :one
SELECT id, model_id, version, base_model, lora_adapter, parent_version, artifact_uri, tags, status, created_by, created_at, updated_at
FROM models WHERE id = $1::uuid
`

type GetModelVersionRow struct {
	ID            string    `json:"id"`
	ModelID       string    `json:"model_id"`
	Version       string    `json:"version"`
	BaseModel     *string   `json:"base_model"`
	LoraAdapter   *string   `json:"lora_adapter"`
	ParentVersion *string   `json:"parent_version"`
	ArtifactUri   *string   `json:"artifact_uri"`
	Tags          []byte    `json:"tags"`
	Status        string    `json:"status"`
	CreatedBy     *string   `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetModelVersion(ctx context.Context, id string) (GetModelVersionRow, error) {
	row := q.db.QueryRow(ctx, getModelVersion, id)
	var i GetModelVersionRow
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.BaseModel,
		&i.LoraAdapter,
		&i.ParentVersion,
		&i.ArtifactUri,
		&i.Tags,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelVersions = `-- name: ListModelVersions :many

SELECT id, model_id, version, base_model, lora_adapter, parent_version, artifact_uri, tags, status, created_by, created_at, updated_at
FROM models
ORDER BY model_id ASC, created_at DESC
`

type ListModelVersionsRow struct {
	ID            string    `json:"id"`
	ModelID       string    `json:"model_id"`
	Version       string    `json:"version"`
	BaseModel     *string   `json:"base_model"`
	LoraAdapter   *string   `json:"lora_adapter"`
	ParentVersion *string   `json:"parent_version"`
	ArtifactUri   *string   `json:"artifact_uri"`
	Tags          []byte    `json:"tags"`
	Status        string    `json:"status"`
	CreatedBy     *string   `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// C1：模型注册中心查询（独立 model registry）。
func (q *Queries) ListModelVersions(ctx context.Context) ([]ListModelVersionsRow, error) {
	rows, err := q.db.Query(ctx, listModelVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelVersionsRow{}
	for rows.Next() {
		var i ListModelVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Version,
			&i.BaseModel,
			&i.LoraAdapter,
			&i.ParentVersion,
			&i.ArtifactUri,
			&i.Tags,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsByModelID = `-- name: ListVersionsByModelID :many
SELECT id, model_id, version, base_model, lora_adapter, parent_version, artifact_uri, tags, status, created_by, created_at, updated_at
FROM models WHERE model_id = $1
ORDER BY created_at DESC
`

type ListVersionsByModelIDRow struct {
	ID            string    `json:"id"`
	ModelID       string    `json:"model_id"`
	Version       string    `json:"version"`
	BaseModel     *string   `json:"base_model"`
	LoraAdapter   *string   `json:"lora_adapter"`
	ParentVersion *string   `json:"parent_version"`
	ArtifactUri   *string   `json:"artifact_uri"`
	Tags          []byte    `json:"tags"`
	Status        string    `json:"status"`
	CreatedBy     *string   `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListVersionsByModelID(ctx context.Context, modelID string) ([]ListVersionsByModelIDRow, error) {
	rows, err := q.db.Query(ctx, listVersionsByModelID, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionsByModelIDRow{}
	for rows.Next() {
		var i ListVersionsByModelIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Version,
			&i.BaseModel,
			&i.LoraAdapter,
			&i.ParentVersion,
			&i.ArtifactUri,
			&i.Tags,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerModelVersion = `-- name: RegisterModelVersion :one
INSERT INTO models (model_id, version, base_model, lora_adapter, parent_version, artifact_uri, tags, status, created_by)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7::jsonb, $8, $9
)
RETURNING id
`

type RegisterModelVersionParams struct {
	ModelID       string  `json:"model_id"`
	Version       string  `json:"version"`
	BaseModel     *string `json:"base_model"`
	LoraAdapter   *string `json:"lora_adapter"`
	ParentVersion *string `json:"parent_version"`
	ArtifactUri   *string `json:"artifact_uri"`
	Tags          []byte  `json:"tags"`
	Status        string  `json:"status"`
	CreatedBy     *string `json:"created_by"`
}

func (q *Queries) RegisterModelVersion(ctx context.Context, arg RegisterModelVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, registerModelVersion,
		arg.ModelID,
		arg.Version,
		arg.BaseModel,
		arg.LoraAdapter,
		arg.ParentVersion,
		arg.ArtifactUri,
		arg.Tags,
		arg.Status,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setModelArtifact = `-- name: SetModelArtifact :exec
UPDATE models SET artifact_uri = $1, updated_at = now()
WHERE id = $2::uuid
`

type SetModelArtifactParams struct {
	ArtifactUri *string `json:"artifact_uri"`
	ID          string  `json:"id"`
}

func (q *Queries) SetModelArtifact(ctx context.Context, arg SetModelArtifactParams) error {
	_, err := q.db.Exec(ctx, setModelArtifact, arg.ArtifactUri, arg.ID)
	return err
}

const updateModelVersionStatus = `-- name: UpdateModelVersionStatus :one
UPDATE models SET status = $1, updated_at = now()
WHERE id = $2::uuid
RETURNING model_id, version
`

type UpdateModelVersionStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

type UpdateModelVersionStatusRow struct {
	ModelID string `json:"model_id"`
	Version string `json:"version"`
}

func (q *Queries) UpdateModelVersionStatus(ctx context.Context, arg UpdateModelVersionStatusParams) (UpdateModelVersionStatusRow, error) {
	row := q.db.QueryRow(ctx, updateModelVersionStatus, arg.Status, arg.ID)
	var i UpdateModelVersionStatusRow
	err := row.Scan(&i.ModelID, &i.Version)
	return i, err
}
