// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: service_instance.sql

package sqlcgen

import (
	"context"
)

const deregisterServiceInstance = `-- name: DeregisterServiceInstance :execrows
DELETE FROM service_instances WHERE name = $1
`

func (q *Queries) DeregisterServiceInstance(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deregisterServiceInstance, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const heartbeatServiceInstance = `-- name: HeartbeatServiceInstance :execrows
UPDATE service_instances
   SET last_heartbeat_at = now(), last_checked_at = now(), status = 'healthy', updated_at = now()
 WHERE name = $1
`

// 心跳：刷新戳并（若曾被判 unreachable）复活为 healthy。
func (q *Queries) HeartbeatServiceInstance(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatServiceInstance, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerServiceInstance = `-- name: RegisterServiceInstance :one

INSERT INTO service_instances (
    name, base_url, model_id, kind, gpu_id, routing_role, metadata,
    status, last_heartbeat_at, last_checked_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    'healthy', now(), now()
)
ON CONFLICT (name) DO UPDATE SET
    base_url        = EXCLUDED.base_url,
    model_id        = EXCLUDED.model_id,
    kind            = EXCLUDED.kind,
    gpu_id          = EXCLUDED.gpu_id,
    routing_role    = EXCLUDED.routing_role,
    metadata        = EXCLUDED.metadata,
    status          = 'healthy',
    last_heartbeat_at = now(),
    last_checked_at = now(),
    updated_at      = now()
RETURNING name, status
`

type RegisterServiceInstanceParams struct {
	Name        string  `json:"name"`
	BaseUrl     string  `json:"base_url"`
	ModelID     *string `json:"model_id"`
	Kind        string  `json:"kind"`
	GpuID       *string `json:"gpu_id"`
	RoutingRole *string `json:"routing_role"`
	Metadata    []byte  `json:"metadata"`
}

type RegisterServiceInstanceRow struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// 服务注册表（5B.2）：注册/心跳/注销 + TTL 清扫。
// 注册或重注册（按 name upsert）：刷新元数据、置 healthy、打心跳戳。
func (q *Queries) RegisterServiceInstance(ctx context.Context, arg RegisterServiceInstanceParams) (RegisterServiceInstanceRow, error) {
	row := q.db.QueryRow(ctx, registerServiceInstance,
		arg.Name,
		arg.BaseUrl,
		arg.ModelID,
		arg.Kind,
		arg.GpuID,
		arg.RoutingRole,
		arg.Metadata,
	)
	var i RegisterServiceInstanceRow
	err := row.Scan(&i.Name, &i.Status)
	return i, err
}

const sweepStaleServiceInstances = `-- name: SweepStaleServiceInstances :many
UPDATE service_instances
   SET status = 'unreachable', updated_at = now()
 WHERE last_heartbeat_at IS NOT NULL
   AND last_heartbeat_at < now() - make_interval(secs => $1::double precision)
   AND status <> 'unreachable'
RETURNING name
`

// TTL 清扫：超时未心跳者置 unreachable；NULL 心跳（静态种子）不动。
func (q *Queries) SweepStaleServiceInstances(ctx context.Context, ttlSeconds float64) ([]string, error) {
	rows, err := q.db.Query(ctx, sweepStaleServiceInstances, ttlSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
